### ISSUE TITLE
[ToDo] Login & Dashboard

### ISSUE THREAD

**Issue by designDefined** [xction-dev/xflix#13]
## 요약
- 담당자:
- 마감 기한: 23-08-18
- 할 일 요약: Login, Dashboard 페이지 만들기

## 작업 내용
- [x] Login Page 만들기
- [x] Dashboard Page 만들기

### 레이아웃
[로그인 피그마](https://www.figma.com/file/DsGVFoEZkGKBYpWMMjCcyv/Xflix?type=design&node-id=1-2&mode=design&t=aIRoEdxzYKOyFvP5-0)
[대시보드 피그마](https://www.figma.com/file/DsGVFoEZkGKBYpWMMjCcyv/Xflix?type=design&node-id=5-3&mode=design&t=aIRoEdxzYKOyFvP5-0)

### Dashboard
- 라우팅: `/dashboard`
- 주요 컴포넌트: Header, Curation Carousel, Content Card

__Header__
- Xflix 로고 클릭 시 `/dashboard`로 이동합니다.
- 로그인 버튼 클릭 시 `/login`으로 이동합니다.
- layout.js에 배치할 필요 없이 그냥 페이지 내부의 컴포넌트로 배치해주세요!

__Curation Carousel__
- `/mock/curations.json`의 데이터를 이용합니다.
- 가로폭을 넘어갈 경우 각각 가로 스크롤이 가능합니다.
- 주의사항
  - css flex를 이용하여 만들어주시기 바랍니다.

__Content Card__
- 클릭 시 content 데이터의 type에 따라
  - youtube: `/play/${id}`로 이동합니다.
  - writing: url 그대로 이동합니다.
- 피그마 상의 회색 배경에는 썸네일 이미지가 들어갑니다
  - 이미지 비율이 안 맞을 경우 이미지가 가운데 정렬되어 상하좌우가 모두 잘리게끔 해주세요

### Login
- 라우팅: `/login`
- 주요 컴포넌트: Header, ID / Password Input, 확인 버튼

__Header__
Dashboard와 동일

__ID / Password Input__
- 입력이 가능합니다.
- 입력한 값을 useState로 저장해놓습ㄴ다.

__확인 버튼__
- 마우스 hover 시 배경 색이 옅어집니다.
- 클릭 시에는 별도의 기능 없이 `/dashboard`로만 이동합니다.

## 주의 사항
- 컴포넌트는 `src/components/페이지 명/컴포넌트 명`으로 디렉토리 만드시고, 그 내부에 js와 css파일 모두 넣어주세요!
  파일 구조 예시:
  - src
    - components
      - Login
        - IdInput
          - IdInput.js
          - IdInput.css
       - SubmitButton
         - SubmitButton.js
         - SubmitButton.css 
- 위의 피그마와 상세 스펙을 참고하시고, 불분명한 부분은 바로 질문해주세요!

**Comment by nuagenic** [comment]
@designDefined components의 파일명 컨벤션은 위 예시에 적어주신 대로 폴더명을 그대로 갖고 와서 사용하나요? 코딩 애플에서 app 내에 디렉토리 만들 때에는 page.js를 이용하길래 여쭤봅니다~
예시: app/dashboard/page.js

**Comment by designDefined** [comment]
@nuagenic 넵 컴포넌트 파일명은 뭐 크게 상관있진 않지만, 컴포넌트 이름과 동일하게 짓는게 일반적입니다!
예를 들어 `<SomeComponent/>`라는 컴포넌트를 만든다면 파일명도 `SomeComponent.js`로 짓고, css도 `SomeComponent.css`로 지은 다음 둘을 `/SomeComponent`라는 디렉토리 안에 함께 넣는 것이지요. 요런 방법을 추천드립니다

**Comment by nuagenic** [comment]
@designDefined css 작업 시 width, height, margin 등은 px로 작업하는 게 맞나요? 크기 조절을 어떻게 하면 좋을지 모르겠어서 여쭤봅니다~

**Comment by designDefined** [comment]
@nuagenic 디자인이 세세하게 되어있는 게 아니다보니, css 작업은 본인의 판단에 따라 해주시면 됩니다. 
예를 들어 이렇게 고민해보면 좋을 것 같습니다.
- Card 같이 화면 크기가 달라져도 고정된 크기를 가질 것 같은 요소들은 `px`을 사용
- Header같이 항상 화면의 가로폭을 가득 채워야 할 요소들은 `vw`나 `%`를 사용

**Comment by nuagenic** [comment]
@designDefined curations.json에서
id 0번 content의 thumbnail 주소 한번만 확인해주실 수 있나요?
이미지 형태가 아닌 것 같습니다

**Comment by nuagenic** [comment]
글고 혹시 figma에 사용하신 xction 로고 이미지 파일로도 있나요??

**Comment by nuagenic** [comment]
넵 감사합니다~!!
