### ISSUE TITLE
[ANNOUNCEMENT] yarn 설치

### ISSUE THREAD

**Issue by designDefined** [xction-dev/xflix#6]
# yarn 설치

## 개요
현재는 npm으로 관리되고 있는 패키지를 yarn으로 바꿔야 합니다.
먼저 yarn을 개발 환경에 글로벌하게 설치한 후, npm을 현재 프로젝트에서 사용할 yarn classic으로 변경하는 두 작업이 필요합니다.

혹시 yarn을 이미 설치하였다면, -v로 버전 확인해주시고
1.22.19이면: 2c부터 진행
3.6.X이면: 2a부터 진행하시면 됩니다!

## 1. yarn 설치하기

yarn 설치에 관한 내용은 [공식 홈페이지](https://yarnpkg.com/getting-started/install)에도 잘 나와있습니다. 제일 첫 번째로 나오는 방법대로 선택하시면 됩니다. 

### a. node 버전 확인
터미널에서 `node -v` 명령어로 node 버전을 확인합니다. 혹시 표시되는 버전이 16.10 이하라면 [nodejs 홈페이지](https://nodejs.org/en)에 나오는 LTS 버전*을 설치하시면 되겠습니다(또는 nvm 이용)

### b. yarn 설치
위의 링크를 따라 corepack을 enable 한 후, `stable version`을 설치하시면 되겠습니다.

### c. yarn 설치 확인
터미널에서 `yarn -v` 명령어로 버전을 확인합니다. 3.6.0이면 정상입니다

## 2. yarn 버전 명시하기 & npm

우리는 위의 튜토리얼에 따라 yarn berry(3.6.0 버전)을 설치했지만, 이 프로젝트에서 실제로 사용할 것은 yarn classic 입니다. 따라서 버전을 변경해야 합니다....만 제가 `main` 브랜치에 세팅을 해놓았으니 아래대로 하시면 됩니다.

### a. main 브랜치로 pull
혹시 작업 중이던 게 있다면 저장 후 (commit이나 stash) `main` 브랜치로 이동 후 pull 해주세요.

### b. yarn 버전 확인
`yarn -v`로 yarn의 버전이 1.22.19(classic 버전)임을 확인하세요

### c. yarn으로 패키지들 재설치
`node_modules` 폴더를 삭제하고, 혹시 package-lock.json 파일이 남아있다면 이것도 삭제한 후 
터미널에서 `yarn` 명령어로 패키지들을 다시 설치합니다.
설치가 끝나면 `yarn dev`로 개발서버가 제대로 실행되는 지 확인해주세요

## 3. 작업이 끝나면
문제 없이 작업이 끝났다면 저에게 말씀해주세요!
혹시 진행중이던 작업이 있다면 main으로 rebase후 진행해주시면 되겠습니다~

**Comment by bubblelim** [comment]
@designDefined 1-b까진 어찌저찌 된 것 같은데, 1-c에서는 무슨 패키지를 재설치해야 될까요? 우선 node-modules 폴더와 package-lock.json 파일은 없습니다.

**Comment by nuagenic** [comment]
@designDefined 설치 완료했고 yarn dev 확인 마쳤습니다~

**Comment by designDefined** [comment]
@bubblelim package-lock이랑 node_modules는 npm으로 패키지 설치를 했을때 생기는 폴더입니다! 없다면 그냥 yarn 으로 최초설치 하면 됩니다!
패키지는 명령어 yarn으로 자동 설치 가능합니다~~

**Comment by bubblelim** [comment]
@designDefined 아 그러네요 ㅋㅋㅋ 저도 설치 완료했고 yarn dev확인했습니다~~

**Comment by yunsik29** [comment]
이미 1.22.19 버전 설치되있고 yarn dev 확인했습니다~

**Comment by bubblelim** [comment]
@designDefined 아 죄송요 다 잘 끝냈습니다~~
